GHA to auto-update snippets in dashboard
Nexmo/github-actions pull request #24
Opened 2021-03-29 18:19 UTC by slorello89

2021-04-06 19:42 UTC, dragonmantank requested changes

2021-04-06 19:42 UTC, dragonmantank commented on codesnippets-auto-pr/Dockerfile
> +COPY ./messages.json /fixures/
Should this be `fixtures`?

2021-04-06 20:34 UTC, slorello89 commented on codesnippets-auto-pr/Dockerfile
> +COPY ./messages.json /fixures/
it actually doesn't belong at all.

2021-04-09 15:38 UTC, dragonmantank approved these changes
LGTM

2021-04-09 15:39 UTC, merged